- .github/workflows/lint-and-test.yaml
Replicates the local directory structure that I set up on my machine:
```
$WORKSPACE/nanobind-bazel
/nanobind_example
```
Since the bzlmod path is hardcoded right now, that setup needs to be replicated in CI.
> Add GitHub Actions job building and testing wjakob/nanobind_example

- BUILD
- build_defs.bzl
- helpers.bzl
- nanobind.BUILD
Still in progress, the extension name is not correct yet (needs to be `.abi3.so` in the SABI case). 
However, I'm not sure how this is solvable elegantly outside of a completely custom rule implementation for `nanobind_extension`.
Usage:
```shell
bazel build //src:my_ext --@rules_python//python/config_settings:python_version=$MAJOR.$MINOR[.$PATCH] --@nanobind_bazel//:py-limited-api=cp312
```
Currently only `cp312` and `cp313` are supported as targetable Python ABI versions.
> Implement stable ABI builds

- .github/workflows/lint-and-test.yaml
Only applies to CPython>=3.12.
> Add abi3audit check for stable ABI violations to CI

- build_defs.bzl
- helpers.bzl
- internal_configure.bzl
- nanobind.BUILD
Results in a `@nanobind//:libnanobind` target producing a `libnanobind.a` file.
> Make static linking for `nanobind_extension` optional

- MODULE.bazel
- internal_configure.bzl
In response to a recent issue on versioning ideas for nanobind-bazel. The way to change versions is now to use a `git_override`.
> Remove version parsing from `nanobind_bazel`, pin fixed version instead

- nanobind.BUILD
Follows the official documentation's guidance that LTO is not strictly necessary due to the library component. As an alternative, users can give the `thin_lto` feature to a nanobind_extension instead.
The second `-Wl,-dead_strip` removal is due to it appearing twice in the generated linker command. I also saw a missing symbol error during a stubgen attempt earlier, which has since disappeared.
> Remove default LTO options, dead_strip in MacOS linker options

- build_defs.bzl
Mirrors the CMake NB_DOMAIN setting, resulting in an extension-scoped `-DNB_DOMAIN=$DOMAIN` define value. Hence, it should appear in `local_defines`.
> Add nanobind domain setting to `nanobind_extension`

- .github/workflows/lint-and-test.yaml
- BUILD
- build_defs.bzl
- helpers.bzl
- nanobind.BUILD
> Flip minsize option to True by default

- BUILD
- build_defs.bzl
- helpers.bzl
- nanobind.BUILD
Previously, mangled symbols would show up in the exports list on MacOS (as seen in `nm -U` commands on the Python bindings shared objects).
The fix here is to supply `-Wl,-x` and `-Wl,-S` to the macOS linker, which ends up producing the same output as CMake does (verified on my machine).
Similarly, after checking the Linux ninja build manifest, Linux needs a `-Wl,-s`.
> Add strip optimizations to linker flags

- build_defs.bzl
- helpers.bzl
- nanobind.BUILD
- robin_map.BUILD
`-fexceptions` seems to be the default for gcc and clang, anyways.
The common options are factored out into a new helper function, with the option of a `mode` argument, which is either user-facing (the default, adds `-fno-stack-protector` on Unix systems) or lib-facing (no-op).
> Refactor common build opts, build robin_map without -fexceptions

- MODULE.bazel
- README.md
nanobind-bazel was released on BCR. Also, a stale comment about version parsing was fixed.
> Update README to reflect project changes

- MODULE.bazel
- internal_configure.bzl
- nanobind.BUILD
Changes needed to make the upgrade work:
1) Bump robin-map to v1.3.0. This is due to the added API `erase_fast(iterator pos)`
contributed to robin-map that is used in nanobind to avoid expensive lookups in hashmaps.
2) Bump nanobind to v2.0.0. I had to exclude the `nb_combined.cpp` file to fix a
compilation error when building libnanobind.
Also includes some core dependency updates in fff5a8486806d5a829580014478f8b9c12cd607d.
Addresses #26.
Source thread for the robin-map change is in https://github.com/Tessil/robin-map/pull/76, backstory is contained in https://github.com/wjakob/nanobind/issues/507 and references therein.
> Update nanobind to v2.0.0

- MODULE.bazel
Increases the compatibility level to 2 after the major version bump in nanobind.
> Prepare v2.0.0 release of nanobind-bazel

- build_defs.bzl
Visibility of the `nanobind_extension` target can be set implicitly in its keyword arguments, but was not propagated to the resulting build targets, in particular the produced shared object(s).
Fixes #29.
> Propagate visibilities to created nanobind extension libs

- README.md
Include examples for a git_override, e.g. for trying out pre-release nanobind versions, and local_path_override for local development.
Mention that the minimum Bazel necessary is v6.4.0.
> Clarify usage instructions, Bazel version restrictions

- README.md
- build_defs.bzl
Equivalent to a native `cc_shared_library` with a static nanobind dependency.
This target enables linking multiple extensions with a single shared nanobind target, producing smaller binding sizes.
Closes #25.
Still TODO: Avoid auto-injection of `@nanobind` into the `nanobind_extension` deps, so that we don't link nanobind multiple times.
Reviews and opinions welcome.
> Add `nanobind_shared_library` rule

- .github/workflows/lint-and-test.yaml
- BUILD
- MODULE.bazel
- build_defs.bzl
- internal_configure.bzl
- nanobind.BUILD
- stubgen_wrapper.py
- typing_extensions.BUILD
Adds `typing_extensions` as a unconditional dependency for the stubgen target.
The plan is to wrap the `py_binary` into a nanobind stubgen rule that lives in the same file as all other rules.
Closes #14.
> Expose nanobind's stubgen as a `py_binary`

- .pre-commit-config.yaml
- BUILD
- MODULE.bazel
- helpers.bzl
- internal_configure.bzl
- nanobind.BUILD
Contains a flag for the `NB_FREE_THREADED` define, which goes into the compilation of libnanobind.
Closes #37.
> Add free-threading support

- MODULE.bazel
It broke Bazel 6.x compatibility, and was not required.
rules_python@0.37.0 is now depended on for Python 3.13 support, which is good to have for free-threading (the headline feature of nanobind v2.2.0).
> Revert rules_cc bump

- .github/workflows/lint-and-test.yaml
Also contains minor other tweaks, such as using build as a build frontend, and checking built wheels for CPython>=3.12 from now on.
-----------
Needs an upstream change in the nanobind_example's setup.py file (or a toolchain declaration in MODULE.bazel).
> Add CPython 3.13 to CI test matrix

- .github/workflows/lint-and-test.yaml
- .pre-commit-config.yaml
- fixup_module_bazel.py
- helpers.bzl
Done via a small Python script for portability. This ensures that we test the nanobind example build against the latest version in CI.
> ci: Patch MODULE.bazel in nanobind example

- .github/workflows/lint-and-test.yaml
- stubgen.patch
Currently, it's a string comparison, which means ">=" is checked by character. Hence, we invoke abi3audit even for Python 3.8 and 3.9, which is useless.
This might break if free-threading gets thrown into the mix, which carries a "t" suffix in its version, preventing integer casting.
> Fix job skip condition by interpreting Python version as int

- BUILD
This enables users to consume the internal nanobind library for their own purposes, exposing it as `@nanobind_bazel//:nanobind`.
Related to #48.
> Add alias forwarding internal `@nanobind` to users

- BUILD
- MODULE.bazel
- helpers.bzl
Eliminates the need for custom settings, and another flag to set for consuming builds.
This requires a bump to rules_python v0.39.0, which introduced free-threading support.
> Use `rules_python` free-threading config settings

- .github/workflows/lint-and-test.yaml
That's per NumPy Python support policy, which considers Python versions only released within the last 48 months.
No updates to the stubgen wrapper yet, so that Python 3.8 should still work, though untested. I could run pyupgrade for 3.9 later to bump to Python 3.9 syntax, for example by adding a ruff job.
> Drop Python 3.8 and 3.9 from GitHub Actions test matrix

- MODULE.bazel
- internal_configure.bzl
Includes a module update as well as a nanobind repo update.
No v2.3.0, since nanobind skipped over it by mistake.
> Bump to v2.4.0

- MODULE.bazel
- build_defs.bzl
- stubgen_wrapper.py
To support producing stubs for submodules.
#43
> feat: support recursive stubgen

- .pre-commit-config.yaml
- BUILD
- helpers.bzl
Given as `@nanobind_bazel//:py-limited-api=cp314`. This enables builds with alpha/beta/rc CPython 3.14 toolchains targeting the stable ABI from that version onwards.
> Add Python 3.14 stable ABI support

- stubgen_wrapper.py
This was fixed in v2.5.0, so we can remove the path fixup section.
> stubgen: Remove path fixup workaround

- .pre-commit-config.yaml
- build_defs.bzl
- nanobind.BUILD
- robin_map.BUILD
This is important since native aliases to these rules will be removed eventually in newer Bazel versions.
The changeset is a result of autofixes by buildifier when bumped to v8.0.1.
> chore: Switch to non-native rules to maintain new Bazel compatibility

- MODULE.bazel
This is necessary due to a yanked rules_cc version showing up in the dependency graph for Bazel 7.
> Bump rules_cc and rules_python dependencies

- nanobind_bazel_local_override.patch
After the version was bumped to v2.5.0.
> chore: Renew nanobind_example MODULE.bazel patch

- .pre-commit-config.yaml
- build_defs.bzl
This is an autofix by the most recent buildifier.
> buildifier: Import cc_shared_library from proper submodule of rules_cc

- internal_configure.bzl
Mirrors the same bump in the nanobind repository.
> chore: Bump robin-map to v1.4.0

- internal_configure.bzl
> chore: Bump typing-extensions to v4.13.2

- build_defs.bzl
Mirrors the recently added, experimental `cc_static_library` feature. This produces a single static library containing nanobind as a direct dependency, which is also statically linked.
Needs the `--experimental_cc_static_library` flag to work, see the Bazel docs at https://bazel.build/reference/be/c-cpp#cc_static_library.
> feature: Add `nanobind_static_library` macro

- BUILD
Previously, nanobind_bazel implicitly relied on its top-level attributes being publicly visible, since the nanobind built in the module extension needs some of them to decide which options and defines to set for the build.
To fix, explicitly set visibilities on the used settings and flags. For simplicity, go with public visibility, since other downstream users might want to consume these attributes as well.
Closes #70.
> Fix visibilities of top-level build flags and settings

- helpers.bzl
Currently, nanobind can only be compiled with exceptions and rtti flags ([here is the proof](https://nanobind.readthedocs.io/en/latest/faq.html#can-i-use-nanobind-without-rtti-or-c-exceptions)). By default these are on, but if I try to use my own toolchain with `-fno-exceptions` and `-fno-rtti` it breaks nanobind.
I suggest to enable rtti and exceptions explicitly, so it will override toolchain options and nanobind will compile anyway. This helped in my case, I hope it will help others too
> Added `-fexceptions` and `-frtti` flags into nb_common_opts
